[workspace]
members = [
    "crates/atoma-api",
    "crates/atoma-kernels",
    "crates/backends",
    "crates/backends/vllm",
    "crates/models",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.89"
atoma-backends = { path = "crates/backends" }
atoma-kernels = { path = "crates/atoma-kernels" }
axum = "0.7"
bindgen_cuda = "0.1.5"
candle-core = "0.9.2-alpha.1"
candle-examples = "0.9.2-alpha.1"
candle-nn = "0.9.2-alpha.1"
candle-transformers = "0.9.2-alpha.1"
clap = "4.5.18"
config = "0.14.0"
cuda-runtime-sys = "0.3.0-alpha.1"
cudarc = { version = "0.17.3", features = [
    "cublas",
    "cublaslt",
    "cuda-version-from-build-system",
    "curand",
    "driver",
    "dynamic-linking",
    "f16",
    "nvrtc",
    "std",
], default-features = false }
flume = "0.11.0"
futures = "0.3.30"
half = "2.4.1"
hf-hub = "0.3.2"
metrics = "0.23"
metrics-exporter-prometheus = "0.14.0"
models = { path = "crates/models" }
rand = "0.8.5"
serde = "1.0.204"
serde_json = "1.0.120"
serial_test = "3.1.1"
sys-info = "0.9.1"
thiserror = "1.0.64"
tokenizers = "0.19.1"
tokio = "1.40.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
utoipa = "4.2.3"
utoipa-swagger-ui = "7.1.0"
