minimum_prek_version = "0.4.11"

[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-added-large-files"

[[repos.hooks]]
id = "check-case-conflict"

[[repos.hooks]]
id = "check-merge-conflict"

[[repos.hooks]]
id = "check-symlinks"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "check-yaml"

[[repos.hooks]]
id = "detect-private-key"
