[package]
edition = { workspace = true }
license = "Apache-2.0"
name    = "atoma-backends"
version = { workspace = true }

[dependencies]
atoma-vllm-backend = { path = "vllm" }
serde              = { workspace = true, features = [ "derive" ] }

[features]
cuda = [ "atoma-vllm-backend/cuda" ]
nccl = [ "atoma-vllm-backend/nccl", "cuda" ]
